### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zytMatrix** [carter-yagemann/ARCUS#1]
arch/x86/realmode/rm/wakemain.c:2:10: fatal error: boot.h: No such file or directory
 #include "boot.h"
          ^~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.build:259: arch/x86/realmode/rm/wakemain.o] Error 1
make[2]: *** [arch/x86/realmode/Makefile:18: arch/x86/realmode/rm/realmode.bin] Error 2
make[1]: *** [scripts/Makefile.build:403: arch/x86/realmode] Error 2
make: *** [Makefile:952: arch/x86] Error 2

I have tried some versions of OS and gcc. (Ubuntu 18.04+gcc-7.5、Debian 10.0 + gcc-8.3) 
But the error is still exist, can you give me some advices？

**Comment by zytMatrix** [comment]
I think I know why. The directory "ARCUS/linux/arch/x86/" miss a folder “boot” compared the directory in repository Griffin-Trace. I copy it from Griffin-Trace, and I can compile the kernel successfully.

**Comment by carter-yagemann** [comment]
Thanks for catching this. Can you open a pull request with the missing files?

**Comment by carter-yagemann** [comment]
Found it. Not sure why this didn't carry over when we open sourced the code. Thanks!
