### ISSUE TITLE
os.link() Invalid cross-device link

### ISSUE THREAD

**Issue by altodd** [carter-yagemann/ARCUS#2]
After an initial clean install of ARCUS on a Centos8 stream vm where everything seemed to go well I had the test fail at the final step of setting up ARCUS. I modified run-tests.py to show the command used, and ran that command manually. I found that on line 977 of analysis.py when os.link() is called that is failing with "OSError: [Errno 18] Invalid cross-device link:" followed by full path used in arcus to the bin and the tmp directory created. I modified the os.link() call to be a os.symlink() call and the tests work for me now. From y'alls comment about creating symlinks this may have been what you meant to do? os.link() tries to create a hard link and for some reason is failing, I don't have any special mounts but from some research my best guess is that maybe it's because this machine has lvm partitions and python doesn't like that. If your intention was to create symlinks then changing analysis.py:977 from os.link() to os.symlink() is what fixed it for me. If y'all found a reason for hard links maybe it's just something weird I ran into.

**Comment by carter-yagemann** [comment]
Thanks for catching this and making a PR. I don't see any particularly reason to hard link either so your PR looks good to me :+1:
