### ISSUE TITLE
Bugs in Makefile when building build/bin/ptxed

### ISSUE THREAD

**Issue by lh-ycx** [carter-yagemann/ARCUS#9]
Hi, @carter-yagemann. Recently I'm setting up ARCUS using a physical machine under Ubuntu 18.04. I choose the Perf tracing method and it looks good (it outputs `perf.data` though I have not verified it). 

Then I follow the instructions in [ARCUS Setup](https://github.com/carter-yagemann/ARCUS/blob/master/docs/arcus-setup.md). I encounter the following problems:

**1. Makefile is overwritten by cmake**

When I compile the disassembler, I get the following error:

------------------------------------------------ Below is the error report ------------------------------------------------
cmake -DPTDUMP=ON -DPTXED=ON -DPTTC=ON -DSIDEBAND=ON -DPEVENT=ON -DFEATURE_ELF=ON -DFEATURE_THREADS=ON -DXED_INCLUDE=./obj/wkit/include/xed -DXED_LIBDIR=./obj/ -B build ./libipt/
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found UnixCommands: /bin/bash  
-- Configuring done
-- Generating done
-- **Build files have been written to: /home/ycx/Downloads/ARCUS-master/tools/pt**
cmake --build build
Error: /home/ycx/Downloads/ARCUS-master/tools/pt/build is not a directory
Makefile:15: recipe for target 'build/bin/ptxed' failed
make: *** [build/bin/ptxed] Error 1
------------------------------------------------ end of error report ------------------------------------------------

I've highlighted the root cause of the problem: cmake generates the Makefile (the one to make ptxed) to the place where the parent Makefile (the one to make pt) lies in. 

My cmake version is 3.10.2 and I'm not sure if older or newer one would face the same problem. To fix this problem, we just make cmake generate the Makefile in the write place. I modify the `tools/pt/Makefile` as follow (the modification is highlighted):

build/bin/ptxed:
	**mkdir -p build
	cd build && \\
	cmake -DPTDUMP=ON -DPTXED=ON -DPTTC=ON -DSIDEBAND=ON -DPEVENT=ON -DFEATURE_ELF=ON -DFEATURE_THREADS=ON -DXED_INCLUDE=./obj/wkit/include/xed -DXED_LIBDIR=./obj/ ../libipt/ && \\
	cd ..**
	cmake --build build

**2. xed-interface.h: No such file or directory**

After solving the first problem, I retry `make` and get the following error:

------------------------------------------------ Below is the error report ------------------------------------------------
[ 73%] Building C object ptxed/CMakeFiles/ptxed.dir/src/ptxed.c.o

cd /home/ycx/Downloads/ARCUS-master/tools/pt/build/ptxed && /usr/bin/cc -DFEATURE_ELF -DFEATURE_PEVENT -DFEATURE_SIDEBAND -DFEATURE_THREADS -DPT_VERSION_BUILD=0 -DPT_VERSION_EXT=\"\" -DPT_VERSION_MAJOR=2 -DPT_VERSION_MINOR=0 -DPT_VERSION_PATCH=4 -D_POSIX_C_SOURCE=200809L -I/home/ycx/Downloads/ARCUS-master/tools/pt/libipt/include -I/home/ycx/Downloads/ARCUS-master/tools/pt/build/libipt/include -I/home/ycx/Downloads/ARCUS-master/tools/pt/build/sideband/include -I/home/ycx/Downloads/ARCUS-master/tools/pt/libipt/pevent/include -I/home/ycx/Downloads/ARCUS-master/tools/pt/libipt/include/posix -I/home/ycx/Downloads/ARCUS-master/tools/pt/libipt/ptxed/include -I/home/ycx/Downloads/ARCUS-master/tools/pt/libipt/ptxed/../libipt/internal/include **-isystem /home/ycx/Downloads/ARCUS-master/tools/pt/build/obj/wkit/include/xed**  -std=c99 -fvisibility=hidden   -o CMakeFiles/ptxed.dir/src/ptxed.c.o   -c /home/ycx/Downloads/ARCUS-master/tools/pt/libipt/ptxed/src/ptxed.c

/home/ycx/Downloads/ARCUS-master/tools/pt/libipt/ptxed/src/ptxed.c:48:10: fatal error: **xed-interface.h: No such file or directory**

 #include <xed-interface.h>
          ^~~~~~~~~~~~~~~~~

------------------------------------------------ end of error report ------------------------------------------------

I also highlight the root cause. The problem is in the `tools/pt/libipt/ptxed/CmakeLists.txt`, where `XED_INCLUDE` and `XED_LIBDIR` are set to ``CACHE PATH`` but it seems that cmake cannot choose a correct path. I'm not familiar with the `CACHE PATH` so I just add the right path in the `CmakeLists.txt`. Bellow is the modified `CmakeLists.txt`.

include_directories(
  include
  ../libipt/internal/include
  **../../obj/wkit/include/xed**
)

link_directories(
  ${XED_LIBDIR}
  **../../obj/wkit/lib**
)

Up to now, I've successfully build ARCUS and pass the unit tests in  [ARCUS Setup](https://github.com/carter-yagemann/ARCUS/blob/master/docs/arcus-setup.md). Also, I will submit a pull request soon. Hope my experience would help somebody else.

**Comment by lh-ycx** [comment]
Pull request #10 submitted for review : )

**Comment by carter-yagemann** [comment]
Hi @lh-ycx, I have verified this bug does occur for cmake 3.10.2. It does _not_ occur in cmake 3.18.4.

Upon investigation, I discovered the `-B` flag for cmake was added in cmake 3.13.0.

**Comment by carter-yagemann** [comment]
PR merged, thanks for your help :+1:
